"""
Pydantic models generated from the OXA JSON Schema.

Do not edit this file directly. Instead, edit the YAML schema files
in the schema/ directory and run `pnpm codegen py`.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field


class Cite(BaseModel):
    """An inline citation to a bibliographic reference."""

    model_config = ConfigDict(strict=True)

    type: Literal["Cite"] = "Cite"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    xref: str = Field(
        description="Reference to the id of a Reference node in the containing document."
    )
    children: list["Inline"] | None = Field(
        default=None,
        description="Optional inline content that overrides generated citation display text.",
    )
    prefix: list["Inline"] | None = Field(
        default=None,
        description="Inline content preceding the citation within its group.",
    )
    suffix: list["Inline"] | None = Field(
        default=None,
        description="Inline content following the citation within its group.",
    )
    display: Literal["author", "date", "full"] | None = Field(
        default=None,
        description="Controls which part of the referenced bibliographic record is rendered.",
    )
    locator: str | None = Field(
        default=None, description="A human-readable locator within the referenced work."
    )
    url: str | None = Field(
        default=None,
        description="A deep link to a specific location in the referenced work.",
    )
    intent: str | None = Field(
        default=None,
        description="The citation intent, typically using a CiTO vocabulary value.",
    )


class CiteGroup(BaseModel):
    """An inline container that groups citations with shared display semantics."""

    model_config = ConfigDict(strict=True)

    type: Literal["CiteGroup"] = "CiteGroup"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    kind: Literal["narrative", "parenthetical"] = Field(
        description="The citation display style shared by the group."
    )
    children: list["Cite"] = Field(description="The citations in the group.")


class Code(BaseModel):
    """A block of preformatted text, typically source code."""

    model_config = ConfigDict(strict=True)

    type: Literal["Code"] = "Code"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    language: str | None = Field(
        default=None, description="The programming language of the code content."
    )
    value: str = Field(description="The code content.")


class CodeCell(BaseModel):
    """An executable block of code that can produce outputs."""

    model_config = ConfigDict(strict=True)

    type: Literal["CodeCell"] = "CodeCell"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    code: str = Field(description="The source code to execute.")
    language: str | None = Field(
        default=None, description="The programming language identifier for the code."
    )
    isEchoed: bool | None = Field(
        default=None, description="Whether the source code is displayed to readers."
    )
    isHidden: bool | None = Field(
        default=None, description="Whether outputs are hidden from readers."
    )


class CodeExpr(BaseModel):
    """An executable expression embedded within prose."""

    model_config = ConfigDict(strict=True)

    type: Literal["CodeExpr"] = "CodeExpr"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    code: str = Field(description="The expression to evaluate.")
    language: str | None = Field(
        default=None,
        description="The programming language identifier for the expression.",
    )


class Document(BaseModel):
    """A document with metadata, title, and block content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Document"] = "Document"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    metadata: dict[str, Any] | None = Field(
        default=None, description="Arbitrary document metadata."
    )
    title: list["Inline"] | None = Field(
        default=None, description="The document title as inline content."
    )
    children: list["Block"] = Field(description="The block content of the document.")


class Emphasis(BaseModel):
    """Emphasized content (typically italicized)."""

    model_config = ConfigDict(strict=True)

    type: Literal["Emphasis"] = "Emphasis"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(description="The inline content to emphasize.")


class Heading(BaseModel):
    """A heading with a level and inline content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Heading"] = "Heading"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    level: int = Field(description="The heading level (1-6).")
    children: list["Inline"] = Field(description="The inline content of the heading.")


class InlineCode(BaseModel):
    """Short fragments of code appearing within prose."""

    model_config = ConfigDict(strict=True)

    type: Literal["InlineCode"] = "InlineCode"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    language: str | None = Field(
        default=None, description="The programming language of the code content."
    )
    value: str = Field(description="The code content.")


class Paragraph(BaseModel):
    """A paragraph of inline content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Paragraph"] = "Paragraph"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(description="The inline content of the paragraph.")


class Reference(BaseModel):
    """A block-level bibliographic record."""

    model_config = ConfigDict(strict=True)

    type: Literal["Reference"] = "Reference"
    id: str = Field(
        description="A unique identifier for the node, used by Cite xref values."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] | None = Field(
        default=None,
        description="Optional inline content for the rendered display of this reference.",
    )
    csl: dict[str, Any] = Field(
        description="A CSL-JSON item object for the bibliographic record."
    )


class Strong(BaseModel):
    """Strongly emphasized content (typically bold)."""

    model_config = ConfigDict(strict=True)

    type: Literal["Strong"] = "Strong"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(description="The inline content to emphasize.")


class Subscript(BaseModel):
    """Content rendered below the baseline (e.g. chemical formulae, variable indices)."""

    model_config = ConfigDict(strict=True)

    type: Literal["Subscript"] = "Subscript"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(
        description="The inline content to render as subscript."
    )


class Superscript(BaseModel):
    """Content rendered above the baseline (e.g. exponents, ordinal suffixes)."""

    model_config = ConfigDict(strict=True)

    type: Literal["Superscript"] = "Superscript"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(
        description="The inline content to render as superscript."
    )


class Text(BaseModel):
    """A text node containing a string value."""

    model_config = ConfigDict(strict=True)

    type: Literal["Text"] = "Text"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    value: str = Field(description="The text content.")


class ThematicBreak(BaseModel):
    """A thematic or structural division between sections of content."""

    model_config = ConfigDict(strict=True)

    type: Literal["ThematicBreak"] = "ThematicBreak"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )


# Union of all block content types.
Block = Annotated[
    Union[Code, CodeCell, Heading, Paragraph, Reference, ThematicBreak],
    Field(discriminator="type"),
]


# Union of all inline content types.
Inline = Annotated[
    Union[
        Cite,
        CiteGroup,
        Text,
        Emphasis,
        CodeExpr,
        InlineCode,
        Strong,
        Subscript,
        Superscript,
    ],
    Field(discriminator="type"),
]


# Rebuild models to resolve forward references
Cite.model_rebuild()
CiteGroup.model_rebuild()
Code.model_rebuild()
CodeCell.model_rebuild()
CodeExpr.model_rebuild()
Document.model_rebuild()
Emphasis.model_rebuild()
Heading.model_rebuild()
InlineCode.model_rebuild()
Paragraph.model_rebuild()
Reference.model_rebuild()
Strong.model_rebuild()
Subscript.model_rebuild()
Superscript.model_rebuild()
Text.model_rebuild()
ThematicBreak.model_rebuild()


__all__ = [
    "Block",
    "Cite",
    "CiteGroup",
    "Code",
    "CodeCell",
    "CodeExpr",
    "Document",
    "Emphasis",
    "Heading",
    "Inline",
    "InlineCode",
    "Paragraph",
    "Reference",
    "Strong",
    "Subscript",
    "Superscript",
    "Text",
    "ThematicBreak",
]
