"""
Pydantic models generated from the OXA JSON Schema.

Do not edit this file directly. Instead, edit the YAML schema files
in the schema/ directory and run `pnpm codegen py`.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field


class Document(BaseModel):
    """A document with metadata, title, and block content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Document"] = "Document"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    metadata: dict[str, Any] | None = Field(
        default=None, description="Arbitrary document metadata."
    )
    title: list["Inline"] | None = Field(
        default=None, description="The document title as inline content."
    )
    children: list["Block"] = Field(description="The block content of the document.")


class Heading(BaseModel):
    """A heading with a level and inline content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Heading"] = "Heading"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    level: int = Field(description="The heading level (1-6).")
    children: list["Inline"] = Field(description="The inline content of the heading.")


class Paragraph(BaseModel):
    """A paragraph of inline content."""

    model_config = ConfigDict(strict=True)

    type: Literal["Paragraph"] = "Paragraph"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(description="The inline content of the paragraph.")


class Strong(BaseModel):
    """Strongly emphasized content (typically bold)."""

    model_config = ConfigDict(strict=True)

    type: Literal["Strong"] = "Strong"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    children: list["Inline"] = Field(description="The inline content to emphasize.")


class Text(BaseModel):
    """A text node containing a string value."""

    model_config = ConfigDict(strict=True)

    type: Literal["Text"] = "Text"
    id: str | None = Field(
        default=None, description="A unique identifier for the node."
    )
    classes: list[str] | None = Field(
        default=None, description="A list of class names for styling or semantics."
    )
    data: dict[str, Any] | None = Field(
        default=None, description="Arbitrary key-value data attached to the node."
    )
    value: str = Field(description="The text content.")


# Union of all block content types.
Block = Annotated[Union[Heading, Paragraph], Field(discriminator="type")]


# Union of all inline content types.
Inline = Annotated[Union[Text, Strong], Field(discriminator="type")]


# Rebuild models to resolve forward references
Document.model_rebuild()
Heading.model_rebuild()
Paragraph.model_rebuild()
Strong.model_rebuild()
Text.model_rebuild()


__all__ = [
    "Block",
    "Document",
    "Heading",
    "Inline",
    "Paragraph",
    "Strong",
    "Text",
]
