//! Rust types generated from the OXA JSON Schema.
//!
//! Do not edit this file directly. Instead, edit the YAML schema files
//! in the schema/ directory and run `pnpm codegen rs`.

// We can't derive Eq because serde_json::Value doesn't implement it (floats can be NaN)
#![allow(clippy::derive_partial_eq_without_eq)]

use monostate::MustBe;
use serde::{Deserialize, Serialize};

/// A block of preformatted text, typically source code.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Code {
    /// The type discriminator for Code nodes.
    pub r#type: MustBe!("Code"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The programming language of the code content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// The code content.
    pub value: String,
}

/// A document with metadata, title, and block content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Document {
    /// The type discriminator for Document nodes.
    pub r#type: MustBe!("Document"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// Arbitrary document metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// The document title as inline content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<Vec<Inline>>,
    /// The block content of the document.
    pub children: Vec<Block>,
}

/// Emphasized content (typically italicized).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Emphasis {
    /// The type discriminator for Emphasis nodes.
    pub r#type: MustBe!("Emphasis"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The inline content to emphasize.
    pub children: Vec<Inline>,
}

/// A heading with a level and inline content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Heading {
    /// The type discriminator for Heading nodes.
    pub r#type: MustBe!("Heading"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The heading level (1-6).
    pub level: i64,
    /// The inline content of the heading.
    pub children: Vec<Inline>,
}

/// Short fragments of code appearing within prose.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InlineCode {
    /// The type discriminator for InlineCode nodes.
    pub r#type: MustBe!("InlineCode"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The programming language of the code content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// The code content.
    pub value: String,
}

/// A paragraph of inline content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Paragraph {
    /// The type discriminator for Paragraph nodes.
    pub r#type: MustBe!("Paragraph"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The inline content of the paragraph.
    pub children: Vec<Inline>,
}

/// Strongly emphasized content (typically bold).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Strong {
    /// The type discriminator for Strong nodes.
    pub r#type: MustBe!("Strong"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The inline content to emphasize.
    pub children: Vec<Inline>,
}

/// Content rendered below the baseline (e.g. chemical formulae, variable indices).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Subscript {
    /// The type discriminator for Subscript nodes.
    pub r#type: MustBe!("Subscript"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The inline content to render as subscript.
    pub children: Vec<Inline>,
}

/// Content rendered above the baseline (e.g. exponents, ordinal suffixes).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Superscript {
    /// The type discriminator for Superscript nodes.
    pub r#type: MustBe!("Superscript"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The inline content to render as superscript.
    pub children: Vec<Inline>,
}

/// A text node containing a string value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Text {
    /// The type discriminator for Text nodes.
    pub r#type: MustBe!("Text"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    /// The text content.
    pub value: String,
}

/// A thematic or structural division between sections of content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThematicBreak {
    /// The type discriminator for ThematicBreak nodes.
    pub r#type: MustBe!("ThematicBreak"),
    /// A unique identifier for the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// A list of class names for styling or semantics.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub classes: Option<Vec<String>>,
    /// Arbitrary key-value data attached to the node.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

/// Union of all block content types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Block {
    Code(Code),
    Heading(Heading),
    Paragraph(Paragraph),
    ThematicBreak(ThematicBreak),
}

/// Union of all inline content types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Inline {
    Text(Text),
    Emphasis(Emphasis),
    InlineCode(InlineCode),
    Strong(Strong),
    Subscript(Subscript),
    Superscript(Superscript),
}
