/**
 * TypeScript types generated from the OXA JSON Schema.
 *
 * Do not edit this file directly. Instead, edit the YAML schema files
 * in the schema/ directory and run `pnpm codegen ts`.
 */

/**
 * A document with metadata, title, and block content.
 */
export interface Document {
  /**
   * The type discriminator for Document nodes.
   */
  type: "Document";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * Arbitrary document metadata.
   */
  metadata: Record<string, unknown>;
  /**
   * The document title as inline content.
   */
  title: Inline[];
  /**
   * The block content of the document.
   */
  children: Block[];
}

/**
 * A heading with a level and inline content.
 */
export interface Heading {
  /**
   * The type discriminator for Heading nodes.
   */
  type: "Heading";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data: Record<string, unknown>;
  /**
   * The heading level (1-6).
   */
  level: number;
  /**
   * The inline content of the heading.
   */
  children: Inline[];
}

/**
 * A paragraph of inline content.
 */
export interface Paragraph {
  /**
   * The type discriminator for Paragraph nodes.
   */
  type: "Paragraph";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data: Record<string, unknown>;
  /**
   * The inline content of the paragraph.
   */
  children: Inline[];
}

/**
 * Strongly emphasized content (typically bold).
 */
export interface Strong {
  /**
   * The type discriminator for Strong nodes.
   */
  type: "Strong";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data: Record<string, unknown>;
  /**
   * The inline content to emphasize.
   */
  children: Inline[];
}

/**
 * A text node containing a string value.
 */
export interface Text {
  /**
   * The type discriminator for Text nodes.
   */
  type: "Text";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data: Record<string, unknown>;
  /**
   * The text content.
   */
  value: string;
}

/**
 * Union of all block content types.
 */
export type Block = Heading | Paragraph;

/**
 * Union of all inline content types.
 */
export type Inline = Text | Strong;
