/**
 * TypeScript types generated from the OXA JSON Schema.
 *
 * Do not edit this file directly. Instead, edit the YAML schema files
 * in the schema/ directory and run `pnpm codegen ts`.
 */

/**
 * A block of preformatted text, typically source code.
 */
export interface Code {
  /**
   * The type discriminator for Code nodes.
   */
  type: "Code";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The programming language of the code content.
   */
  language?: string;
  /**
   * The code content.
   */
  value: string;
}

/**
 * A document with metadata, title, and block content.
 */
export interface Document {
  /**
   * The type discriminator for Document nodes.
   */
  type: "Document";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * Arbitrary document metadata.
   */
  metadata?: Record<string, unknown>;
  /**
   * The document title as inline content.
   */
  title?: Inline[];
  /**
   * The block content of the document.
   */
  children: Block[];
}

/**
 * Emphasized content (typically italicized).
 */
export interface Emphasis {
  /**
   * The type discriminator for Emphasis nodes.
   */
  type: "Emphasis";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The inline content to emphasize.
   */
  children: Inline[];
}

/**
 * A heading with a level and inline content.
 */
export interface Heading {
  /**
   * The type discriminator for Heading nodes.
   */
  type: "Heading";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The heading level (1-6).
   */
  level: number;
  /**
   * The inline content of the heading.
   */
  children: Inline[];
}

/**
 * Short fragments of code appearing within prose.
 */
export interface InlineCode {
  /**
   * The type discriminator for InlineCode nodes.
   */
  type: "InlineCode";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The programming language of the code content.
   */
  language?: string;
  /**
   * The code content.
   */
  value: string;
}

/**
 * A paragraph of inline content.
 */
export interface Paragraph {
  /**
   * The type discriminator for Paragraph nodes.
   */
  type: "Paragraph";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The inline content of the paragraph.
   */
  children: Inline[];
}

/**
 * Strongly emphasized content (typically bold).
 */
export interface Strong {
  /**
   * The type discriminator for Strong nodes.
   */
  type: "Strong";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The inline content to emphasize.
   */
  children: Inline[];
}

/**
 * Content rendered below the baseline (e.g. chemical formulae, variable indices).
 */
export interface Subscript {
  /**
   * The type discriminator for Subscript nodes.
   */
  type: "Subscript";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The inline content to render as subscript.
   */
  children: Inline[];
}

/**
 * Content rendered above the baseline (e.g. exponents, ordinal suffixes).
 */
export interface Superscript {
  /**
   * The type discriminator for Superscript nodes.
   */
  type: "Superscript";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The inline content to render as superscript.
   */
  children: Inline[];
}

/**
 * A text node containing a string value.
 */
export interface Text {
  /**
   * The type discriminator for Text nodes.
   */
  type: "Text";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
  /**
   * The text content.
   */
  value: string;
}

/**
 * A thematic or structural division between sections of content.
 */
export interface ThematicBreak {
  /**
   * The type discriminator for ThematicBreak nodes.
   */
  type: "ThematicBreak";
  /**
   * A unique identifier for the node.
   */
  id?: string;
  /**
   * A list of class names for styling or semantics.
   */
  classes?: string[];
  /**
   * Arbitrary key-value data attached to the node.
   */
  data?: Record<string, unknown>;
}

/**
 * Union of all block content types.
 */
export type Block = Code | Heading | Paragraph | ThematicBreak;

/**
 * Union of all inline content types.
 */
export type Inline =
  | Text
  | Emphasis
  | InlineCode
  | Strong
  | Subscript
  | Superscript;
